package server

import (
	"encoding/json"
	"fmt"
	"net/http"
	"strings"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/metanoia/pali-reader/backend/internal/store"
	"gorm.io/gorm"
)

// Reading the text.
//
// A book is delivered in contiguous runs of segments. The run is a pure
// function of (book, from, count), so it is cached in Redis and shared by
// every reader; the marks that belong to one account are fetched separately.

// apiSegment is the wire form of one segment. Tokens are triples of
// offset/length/flags into Text, which keeps the payload close to the size of
// the text itself — the alternative, sending each word as its own object,
// would roughly triple it.
type apiSegment struct {
	Seq     int      `json:"seq"`
	Para    int      `json:"para"`
	Page    int      `json:"page"`
	Kind    string   `json:"kind"`
	Text    string   `json:"text"`
	HTML    string   `json:"html,omitempty"`
	Tokens  [][3]int `json:"tokens,omitempty"`
	Section string   `json:"section,omitempty"`
	Level   int      `json:"level,omitempty"`
	Markers []string `json:"markers,omitempty"`
	// Variants is [[utf16 offset, reading], ...] — the CST variant readings cut
	// out of Text, each with the position it stood at. Sent whether or not the
	// reader has them switched on: it is a few hundred bytes per run and
	// switching the setting should not need a round trip.
	Variants [][2]any `json:"variants,omitempty"`
	Bold     [][2]int `json:"bold,omitempty"`
	// HasRef is true when a published translation exists for this segment.
	HasRef bool `json:"hasRef,omitempty"`
}

type segmentsResp struct {
	BookID string       `json:"bookId"`
	From   int          `json:"from"`
	Count  int          `json:"count"`
	Total  int          `json:"total"`
	Items  []apiSegment `json:"items"`
	// Done is true when the run reaches the end of the book.
	Done bool `json:"done"`
}

func (s *Server) handleSegments(w http.ResponseWriter, r *http.Request) {
	bookID := chi.URLParam(r, "bookID")
	from := queryInt(r, "from", 1)
	if from < 1 {
		from = 1
	}
	count := queryInt(r, "count", 40)
	if count <= 0 || count > 200 {
		count = 40
	}
	// The reader asks for the whole book's shape on first load so it can
	// scroll continuously; a client that follows the TOC asks for windows.
	cacheKey := "seg:" + bookID + ":" + itoa(from) + ":" + itoa(count)
	var cached segmentsResp
	if s.cache.GetJSON(r.Context(), cacheKey, &cached) {
		writeJSON(w, http.StatusOK, &cached)
		return
	}

	var rows []store.TextSegment
	if err := s.db.WithContext(r.Context()).
		Where("book_id = ? AND seq >= ?", bookID, from).
		Order("seq").Limit(count).Find(&rows).Error; err != nil {
		writeServerErr(w, err)
		return
	}

	out := segmentsResp{
		BookID: bookID, From: from, Count: len(rows),
		Items: make([]apiSegment, 0, len(rows)),
	}
	seqs := make([]int, 0, len(rows))
	for _, row := range rows {
		seqs = append(seqs, row.Seq)
	}
	refSet := s.refSegments(r, bookID, seqs)

	for _, row := range rows {
		it := apiSegment{
			Seq: row.Seq, Para: row.ParaNo, Page: row.PageNo, Kind: row.Kind,
			Text: row.Text, HTML: row.HTML, Section: row.SectionID, Level: row.SectionLvl,
			HasRef: refSet[row.Seq],
		}
		// A decode failure here used to be swallowed, and the reader rendered
		// every word as an empty span. Speak up instead: the corpus is
		// regenerated by the importer, so a mismatch is a build fault, not a
		// data condition to tolerate.
		if row.Tokens != "" {
			if err := json.Unmarshal([]byte(row.Tokens), &it.Tokens); err != nil {
				writeServerErr(w, fmt.Errorf("segment %s#%d tokens: %w", bookID, row.Seq, err))
				return
			}
		}
		if row.Markers != "" {
			if err := json.Unmarshal([]byte(row.Markers), &it.Markers); err != nil {
				writeServerErr(w, fmt.Errorf("segment %s#%d markers: %w", bookID, row.Seq, err))
				return
			}
		}
		if row.Variants != "" {
			if err := json.Unmarshal([]byte(row.Variants), &it.Variants); err != nil {
				writeServerErr(w, fmt.Errorf("segment %s#%d variants: %w", bookID, row.Seq, err))
				return
			}
		}
		out.Items = append(out.Items, it)
	}
	out.Done = len(rows) < count

	// The reader renders a progress bar from the first screen onwards, so the
	// total travels with every window rather than only the first.
	var total int64
	if err := s.db.WithContext(r.Context()).Model(&store.TextSegment{}).
		Where("book_id = ?", bookID).Count(&total).Error; err != nil {
		writeServerErr(w, err)
		return
	}
	out.Total = int(total)

	s.cache.SetJSON(r.Context(), cacheKey, out, s.cfg.SegmentCacheTTL)
	writeJSON(w, http.StatusOK, out)
}

// defaultRefLangs is what the reader asks for unless it says otherwise. Both
// are sent because the settings panel can switch between them without a
// reload, and one language's worth of text is small next to the segment run.
var defaultRefLangs = []string{"zh", "en"}

func splitLangs(raw string) []string {
	if strings.TrimSpace(raw) == "" {
		return defaultRefLangs
	}
	var out []string
	for _, l := range strings.Split(raw, ",") {
		if l = strings.TrimSpace(l); l != "" {
			out = append(out, l)
		}
	}
	if len(out) == 0 {
		return defaultRefLangs
	}
	return out
}

// refSegments returns the set of segment numbers in one run that have a
// published translation, so the client can show the 参考 line only where there
// is something to show.
func (s *Server) refSegments(r *http.Request, bookID string, seqs []int) map[int]bool {
	out := map[int]bool{}
	if len(seqs) == 0 {
		return out
	}
	var found []int
	if err := s.db.WithContext(r.Context()).Model(&store.RefTranslation{}).
		Where("book_id = ? AND segment IN ?", bookID, seqs).
		Pluck("segment", &found).Error; err != nil {
		return out
	}
	for _, f := range found {
		out[f] = true
	}
	return out
}

// ---------------------------------------------------------------------------
// The reader's own marks for a run of segments
// ---------------------------------------------------------------------------

type markNote struct {
	ID        uint      `json:"id"`
	Segment   int       `json:"segment"`
	WordIndex int       `json:"wordIndex"`
	Kind      string    `json:"kind"`
	Body      string    `json:"body"`
	Quote     string    `json:"quote,omitempty"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// markPick is one assertion the reader made about one word. A form can carry
// several at once, which is the point: a Pāḷi surface form is ambiguous, and the
// reader records the candidates before deciding between them.
type markPick struct {
	Key       string `json:"key"`
	Segment   int    `json:"segment"`
	WordIndex int    `json:"wordIndex"`
	Kind      string `json:"kind"`
	Surface   string `json:"surface,omitempty"`
	Lemma     string `json:"lemma,omitempty"`
	LemmaID   uint   `json:"lemmaId,omitempty"`
	POS       string `json:"pos,omitempty"`
	Gender    string `json:"gender,omitempty"`
	Case      string `json:"case,omitempty"`
	Number    string `json:"number,omitempty"`
	Grammar   string `json:"grammar,omitempty"`
	Meaning   string `json:"meaning,omitempty"`
	// MeaningSource names the dictionary a meaning came from, so the chip can
	// say whose wording it is.
	MeaningSource string `json:"meaningSource,omitempty"`
	Split         string `json:"split,omitempty"`
	Note          string `json:"note,omitempty"`
}

type markTranslation struct {
	Segment   int       `json:"segment"`
	Text      string    `json:"text"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type marksResp struct {
	BookID       string            `json:"bookId"`
	Picks        []markPick        `json:"picks"`
	Notes        []markNote        `json:"notes"`
	Translations []markTranslation `json:"translations"`
	// Refs is the published translations for this run, keyed by segment and
	// then by language, so switching the language in the reader's settings does
	// not need another round trip.
	Refs    map[string]map[string]string `json:"refs,omitempty"`
	Segment int                          `json:"segment,omitempty"`
}

// handleMarks returns everything one account has written on a run of segments,
// plus the published translations for the same run. Everything the reader adds
// lives here so the reading surface needs exactly two requests per screen.
func (s *Server) handleMarks(w http.ResponseWriter, r *http.Request) {
	bookID := chi.URLParam(r, "bookID")
	from := queryInt(r, "from", 0)
	to := queryInt(r, "to", 0)
	langs := splitLangs(r.URL.Query().Get("lang"))

	out := marksResp{
		BookID: bookID, Picks: []markPick{}, Notes: []markNote{},
		Translations: []markTranslation{}, Refs: map[string]map[string]string{},
	}

	// Published translations are shared, so they are served even to a guest.
	refTx := s.db.WithContext(r.Context()).Model(&store.RefTranslation{}).
		Where("book_id = ? AND lang IN ?", bookID, langs)
	if from > 0 {
		refTx = refTx.Where("segment >= ?", from)
	}
	if to > 0 {
		refTx = refTx.Where("segment <= ?", to)
	}
	var refs []store.RefTranslation
	if err := refTx.Find(&refs).Error; err != nil {
		writeServerErr(w, err)
		return
	}
	for _, ref := range refs {
		key := itoa(ref.Segment)
		if out.Refs[key] == nil {
			out.Refs[key] = map[string]string{}
		}
		out.Refs[key][ref.Lang] = ref.Text
	}

	u := user(r)
	if u == nil {
		writeJSON(w, http.StatusOK, out)
		return
	}

	scope := func(tx *gorm.DB) *gorm.DB {
		t := tx.WithContext(r.Context()).Where("user_id = ? AND book_id = ?", u.ID, bookID)
		if from > 0 {
			t = t.Where("segment >= ?", from)
		}
		if to > 0 {
			t = t.Where("segment <= ?", to)
		}
		return t
	}

	var picks []store.WordPick
	if err := scope(s.db.DB).Order("segment, word_index, id").Find(&picks).Error; err != nil {
		writeServerErr(w, err)
		return
	}
	for _, p := range picks {
		out.Picks = append(out.Picks, markPick{
			Key: p.Key, Segment: p.Segment, WordIndex: p.WordIndex, Kind: p.Kind,
			Surface: p.Surface, Lemma: p.Lemma, LemmaID: p.LemmaID,
			POS: p.POS, Gender: p.Gender, Case: p.Case, Number: p.Number,
			Grammar: p.Grammar, Meaning: p.Meaning, MeaningSource: p.MeaningSource,
			Split: p.Split, Note: p.Note,
		})
	}

	var notes []store.Note
	if err := scope(s.db.DB).Order("segment, word_index, id").Find(&notes).Error; err != nil {
		writeServerErr(w, err)
		return
	}
	for _, n := range notes {
		out.Notes = append(out.Notes, markNote{
			ID: n.ID, Segment: n.Segment, WordIndex: n.WordIndex, Kind: n.Kind,
			Body: n.Body, Quote: n.Quote, UpdatedAt: n.UpdatedAt,
		})
	}

	var trans []store.Translation
	if err := scope(s.db.DB).Order("segment").Find(&trans).Error; err != nil {
		writeServerErr(w, err)
		return
	}
	for _, t := range trans {
		out.Translations = append(out.Translations, markTranslation{
			Segment: t.Segment, Text: t.Text, UpdatedAt: t.UpdatedAt,
		})
	}

	writeJSON(w, http.StatusOK, out)
}
